# Generated by Django 5.2.10 on 2026-02-01 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Prato')),
                ('description', models.TextField(verbose_name='Descrição do Prato')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Prato')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número da Mesa')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade da Mesa')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponibilidade da Mesa')),
                ('validation_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de Validação')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('type', models.CharField(choices=[('dine-in', 'Consumo no Local'), ('takeaway', 'Para Viagem')], default='dine-in', max_length=50, verbose_name='Tipo de Pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendente/Aguardando Pagamento'), ('queued', 'Na Fila (Cozinha)'), ('preparing', 'Em Preparação'), ('ready', 'Pronto'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=50, verbose_name='Status do Pedido')),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='Pagamento Confirmado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.table', verbose_name='Número da Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.dish', verbose_name='Prato')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
